version: 2

project_name: FileTransfer

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: filetransfer
    main: .
    binary: FileTransfer
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.CommitDate}}

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- .Os }}_{{- .Arch }}

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by GoReleaser.